name: Call Central Workflow

on:
  push:
    branches: [main]

jobs:
  build-push-deploy-docker-image:
    uses: devopsprabin/workflows/.github/workflows/docker-build.yml@main
    secrets:  # ðŸ‘ˆ explicitly pass secrets
      SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
      SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}
      SSH_PORT_DEV: ${{ secrets.SSH_PORT_DEV }}
      SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
    with:
      ssh_enable: "true"
      deploy_folder_path: ${{ vars.DEPLOY_FOLDER_PATH_DEV }}
      deploy_command: ${{ vars.DEPLOY_COMMAND_DEV }}

      